###
POST http://localhost:3000/provider/1/topic/tomatoes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMTIzNDU2Nzg5MCJ9.gyR53IYCDlcnAeCvjC9gq2I5sMtefHHi9fXcMUvuJp0

{
    "message": "some message"
}

###
POST http://localhost:3000/provider/1/topic/tomatoes
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMTIzNDU2Nzg5MCJ9.gyR53IYCDlcnAeCvjC9gq2I5sMtefHHi9fXcMUvuJp0

<message>
some message
</message>

###
POST http://localhost:3000/provider/1/topic/tomatoes
Content-Type: application/x-yaml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMTIzNDU2Nzg5MCJ9.gyR53IYCDlcnAeCvjC9gq2I5sMtefHHi9fXcMUvuJp0

message:
    "some message"

###
POST http://localhost:3000/provider/1/topic/tomatoes
Content-Type: text/tab-separated-values
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMTIzNDU2Nzg5MCJ9.gyR53IYCDlcnAeCvjC9gq2I5sMtefHHi9fXcMUvuJp0

message
some message

###


GET http://localhost:3000/provider/1/from/204f3ebc-c7c0-4d78-a97b-0f3b582c3d84/limit/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMTIzNDU2Nzg5MCJ9.gyR53IYCDlcnAeCvjC9gq2I5sMtefHHi9fXcMUvuJp0

